config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :lists
  resources :tests_specifications, only: [:edit, :update]
  resources :submissions, only: [:index, :create, :show]
  resources :exercises
  resources :languages
  resources :categories

  devise_for :users, controllers: {
    registrations: "users/registrations"
  }

  get "submissions/:id/:page", to: "submissions#show", as: "submission_ide"

  get "users/:id", to: "users#show", as: "user"
  get "users/me/lists", to: "users#lists", as: "user_lists"
  get "users/me/exercises", to: "users#exercises", as: "user_exercises"

  get "/input-generator", to: "input_generator#index"

  get "/home", to: "home#index"

  get "/notifications", to: "notifications#index", as: "notifications"

  root to: "home#index"
end

app/models/list.rb
# frozen_string_literal: true

class List < ApplicationRecord
  include Friendlyable

  belongs_to :owner, class_name: "User"
  has_many :list_exercises
  has_many :exercises, through: :list_exercises

  validates :name, length: {maximum: 60}, presence: true
  validates :privacy, presence: true
  validates :description, length: {maximum: 255}

  enum privacy: [:private_list, :notlisted_list, :public_list]

  after_initialize :set_default_privacy, if: :new_record?

  private

  def set_default_privacy
    self.privacy ||= :private_list
  end
end

app/controllers/lists_controller.rb
# frozen_string_literal: true

class ListsController < ApplicationController
  before_action :set_list, only: [:show, :edit, :destroy]
  before_action :authenticate_user!, only: [:update]

  # GET /lists
  # GET /lists.json
  def index
    @lists = List.all
  end

  # GET /lists/1
  # GET /lists/1.json
  def show
  end

  # GET /lists/new
  def new
    @list = List.new
  end

  # GET /lists/1/edit
  def edit
  end

  # POST /lists
  # POST /lists.json
  def create
    @list = List.new(list_params)

    respond_to do |format|
      if @list.save
        format.html { redirect_to @list, notice: "List was successfully created." }
        format.json { render :show, status: :created, location: @list }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lists/1
  # PATCH/PUT /lists/1.json
  def update
    @list = current_user.lists.friendly.find(params[:id])
    respond_to do |format|
      if @list.update(list_params)
        format.html { redirect_to @list, notice: "List was successfully updated." }
        format.json { render :show, status: :ok, location: @list }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1
  # DELETE /lists/1.json
  def destroy
    @list.destroy
    respond_to do |format|
      format.html { redirect_to lists_url, notice: "List was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_list
    @list = if params[:id] == "history"
      "history"
    else
      List.friendly.find(params[:id])
    end
  end

  # Only allow a list of trusted parameters through.
  def list_params
    params.require(:list).permit(:name, :description, :privacy, :owner_id)
  end
end

app/helpers/lists_helper.rb
# frozen_string_literal: true

module ListsHelper
  def privacy_icon(privacy, options = {})
    case privacy
    when "public_list"
      octicon("globe", options)
    when "notlisted_list"
      octicon("link", options)
    when "private_list"
      octicon("lock", options)
    end
  end
end

app/views/lists/_form.html.slim
-# frozen_string_literal: true
= simple_form_for(@list) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :name
    = f.input :description
    = f.input :privacy
    = f.association :owner

  .form-actions
    = f.button :submit

app/views/lists/edit.html.slim
-# frozen_string_literal: true
= render(Lists::Index::Component.new(user: current_user, list: @list, limit: nil, editing: true))

/h1 Editing list
/
/== render 'form'
/
/=> link_to 'Show', @list
/'|
/=< link_to 'Back', lists_path

app/views/lists/index.html.slim
-# frozen_string_literal: true
h1 Listing lists

table
  thead
    tr
      th Name
      th Description
      th Privacy
      th Owner
      th
      th
      th

  tbody
    - @lists.each do |list|
      tr
        td = list.name
        td = list.description
        td = list.privacy
        td = list.owner
        td = link_to 'Show', list
        td = link_to 'Edit', edit_list_path(list)
        td = link_to 'Destroy', list, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New List', new_list_path

app/views/lists/new.html.slim
-# frozen_string_literal: true
h1 New list

== render 'form'

= link_to 'Back', lists_path

app/views/lists/show.html.slim
-# frozen_string_literal: true

#lists
  = render(Lists::Index::Component.new(user: current_user, list: @list, limit: nil))