config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :lists
  resources :tests_specifications, only: [:edit, :update]
  resources :submissions, only: [:index, :create, :show]
  resources :exercises
  resources :languages
  resources :categories

  devise_for :users, controllers: {
    registrations: "users/registrations"
  }

  get "submissions/:id/:page", to: "submissions#show", as: "submission_ide"

  get "users/:id", to: "users#show", as: "user"
  get "users/me/lists", to: "users#lists", as: "user_lists"
  get "users/me/exercises", to: "users#exercises", as: "user_exercises"

  get "/input-generator", to: "input_generator#index"

  get "/home", to: "home#index"

  get "/notifications", to: "notifications#index", as: "notifications"

  root to: "home#index"
end

app/models/language.rb
# frozen_string_literal: true

class Language < ApplicationRecord
  validates :name, length: {maximum: 30}, presence: true
  validates :cod, presence: true, numericality: {greater_than_or_equal_to: 0,
                                                 less_than: 100}
end

app/controllers/languages_controller.rb
# frozen_string_literal: true

class LanguagesController < ApplicationController
  before_action :set_language, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :ensure_admin!

  # GET /languages
  # GET /languages.json
  def index
    @languages = Language.all
  end

  # GET /languages/1
  # GET /languages/1.json
  def show
  end

  # GET /languages/new
  def new
    @language = Language.new
  end

  # GET /languages/1/edit
  def edit
  end

  # POST /languages
  # POST /languages.json
  def create
    @language = Language.new(language_params)

    respond_to do |format|
      if @language.save
        format.html { redirect_to @language, notice: "Language was successfully created." }
        format.json { render :show, status: :created, location: @language }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @language.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /languages/1
  # PATCH/PUT /languages/1.json
  def update
    respond_to do |format|
      if @language.update(language_params)
        format.html { redirect_to @language, notice: "Language was successfully updated." }
        format.json { render :show, status: :ok, location: @language }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @language.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /languages/1
  # DELETE /languages/1.json
  def destroy
    @language.destroy
    respond_to do |format|
      format.html { redirect_to languages_url, notice: "Language was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_language
    @language = Language.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def language_params
    params.require(:language).permit(:name, :cod)
  end
end

app/helpers/languages_helper.rb
# frozen_string_literal: true

module LanguagesHelper
end

app/views/languages/_form.html.slim
-# frozen_string_literal: true
= simple_form_for @language do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  = f.input :name
  = f.input :cod
  = f.submit

app/views/languages/edit.html.slim
-# frozen_string_literal: true
h1 Editing language

== render 'form'

=> link_to 'Show', @language
'|
=< link_to 'Back', languages_path

app/views/languages/index.html.slim
-# frozen_string_literal: true
h1 Listing languages

table
  thead
    tr
      th Name
      th Cod
      th
      th
      th

  tbody
    - @languages.each do |language|
      tr
        td = language.name
        td = language.cod
        td = link_to 'Show', language
        td = link_to 'Edit', edit_language_path(language)
        td = link_to 'Destroy', language, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Language', new_language_path

app/views/languages/new.html.slim
-# frozen_string_literal: true
h1 New language

== render 'form'

= link_to 'Back', languages_path

app/views/languages/show.html.slim
-# frozen_string_literal: true
p#notice = notice

p
  strong Name:
  = @language.name
p
  strong Cod:
  = @language.cod

=> link_to 'Edit', edit_language_path(@language)
'|
=< link_to 'Back', languages_path