config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :lists
  resources :tests_specifications, only: [:edit, :update]
  resources :submissions, only: [:index, :create, :show]
  resources :exercises
  resources :languages
  resources :categories

  devise_for :users, controllers: {
    registrations: "users/registrations"
  }

  get "submissions/:id/:page", to: "submissions#show", as: "submission_ide"

  get "users/:id", to: "users#show", as: "user"
  get "users/me/lists", to: "users#lists", as: "user_lists"
  get "users/me/exercises", to: "users#exercises", as: "user_exercises"

  get "/input-generator", to: "input_generator#index"

  get "/home", to: "home#index"

  get "/notifications", to: "notifications#index", as: "notifications"

  root to: "home#index"
end

app/controllers/exercises_controller.rb
# frozen_string_literal: true

class ExercisesController < ApplicationController
  before_action :set_exercise, only: [:show, :edit, :update, :destroy]
  before_action :set_exercises_with_search, only: [:index]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :ensure_admin!, except: [:index, :show]

  # GET /exercises
  # GET /exercises.json
  def index
  end

  # GET /exercises/1
  # GET /exercises/1.json
  def show
  end

  # GET /exercises/new
  def new
    @exercise = Exercise.new
    @exercise.content = "parágrafo para explicar o problema\n\n"\
                        "### Entrada\n\n"\
                        "parágrafo para explicar as entradas\n\n"\
                        "### Saída\n\n"\
                        "parágrafo para explicar as saídas\n\n"\
                        "| Exemplos de Entrada | Exemplos de Saída |\n"\
                        "| :- | :- |\n"\
                        "| valor1 | resultado1 |\n"\
                        "| valor2 | resultado2 |\n"\
                        "| valor3 | resultado3 |\n"
  end

  # GET /exercises/1/edit
  def edit
  end

  # POST /exercises
  # POST /exercises.json
  def create
    @exercise = Exercise.new(exercise_params)
    @exercise.author = current_user

    respond_to do |format|
      if @exercise.save
        format.html { redirect_to @exercise, notice: "Exercise was successfully created." }
        format.json { render :show, status: :created, location: @exercise }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @exercise.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /exercises/1
  # PATCH/PUT /exercises/1.json
  def update
    respond_to do |format|
      if @exercise.update(exercise_params)
        format.html { redirect_to @exercise, notice: "Exercise was successfully updated." }
        format.json { render :show, status: :ok, location: @exercise }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @exercise.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /exercises/1
  # DELETE /exercises/1.json
  def destroy
    @exercise.destroy
    respond_to do |format|
      format.html { redirect_to exercises_url, notice: "Exercise was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  def set_exercises_with_search
    search = params[:search]

    @exercises = Exercise.complete.paginate(page: params[:page]).includes(:category).references(:category)

    return unless search

    @exercises = @exercises.complete.fuzzy_search(name: search["name"]) unless search["name"].blank?

    if search["result"]
      @exercises = @exercises.where(id: current_user.solved_exercises) if search["result"] == "Solved"
      @exercises = @exercises.where.not(id: current_user.solved_exercises) if search["result"] == "Unsolved"
    end
    @exercises.where!(level: search["level"]) unless search["level"].blank?
    @exercises.where!(category_id: search["category_id"]) unless search["category_id"].blank?

    sort_exercises
  end

  def sort_exercises
    return unless params[:search]
    return if params[:search]["sort_by"].blank?

    param, option = params[:search]["sort_by"].split(" ")
    @exercises = @exercises.order([[param, option]].to_h)
  end

  def set_exercise
    @exercise = Exercise.find(params[:id])
  end

  def exercise_params
    params.require(:exercise).permit(:category_id, :name, :level, :content)
  end
end

app/helpers/exercises_helper.rb
# frozen_string_literal: true

module ExercisesHelper
  def difficult_color_class(exercise)
    case exercise.level
    when 0..2
      "success"
    when 3..4
      "warning"
    else
      "danger"
    end
  end

  def resolved_percentage_color(percentage)
    if percentage < 5
      "danger"
    elsif percentage < 50
      "warning"
    else
      "success"
    end
  end
end

app/views/exercises/_form.html.slim
-# frozen_string_literal: true
div.row.justify-content-md-center data-controller="exercises easymde"
  div.col.col-md-9.col-lg-8
    = simple_form_for @exercise, wrapper: :vertical_form do |f|
      = f.error_notification
      = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

      = f.input :name, placeholder: 'Exercise title'

      div.row
        div.col-lg-6.col-sm-6.col-12
          = f.association :category,
                          prompt: "Select a category",
                          collection: Category.all
        div.col-lg-6.col-sm-6.col-12
          = f.input :level, prompt: 'Select difficulty level', collection: 1..5

      = f.input :content, input_html: {id:'easymde-input'}

      = f.submit class: 'btn btn-primary btn-block'

app/views/exercises/_show_exercise_content.html.slim
-# frozen_string_literal: true
#exercise-header
  small = "Exercise | #{exercise.id}"
  h1 = exercise.name
  - if exercise.complete?
    small.font-weight-bolder = "TimeLimit: #{exercise.tests_specification.limit_time} | MemLimit: #{exercise.tests_specification.limit_mem}"

#exercise-content
  = markdown exercise.content

app/views/exercises/edit.html.slim
-# frozen_string_literal: true
h1.text-center.text-inverse Editing exercise
hr

== render 'form'

=> link_to 'Show', @exercise
'|
=< link_to 'Back', exercises_path

app/views/exercises/index.html.slim
-# frozen_string_literal: true
- current_user.reload if current_user
h1 Listing exercises

/ need to fix stimulus reflex not working without current_user
- if current_user
  = render(Exercises::SearchCard::Component.new)

#search_results
  - if @exercises.blank?
    .card
      .card-body.text-center
        .text-muted.bold No search results.
  - else
    .row.row-cols-1.row-cols-lg-2.g-4
      - @exercises.each do |exercise|
        .col
          = render(Exercises::Card::Component.new(exercise: exercise))

  br
  = will_paginate @exercises, class: 'apple_pagination'

app/views/exercises/new.html.slim
-# frozen_string_literal: true
h1.text-center.m-3 New exercise

hr

== render 'form'

hr

= link_to 'Back', exercises_path

app/views/exercises/show.html.slim
-# frozen_string_literal: true
div.row.justify-content-md-center
  div.col.col-md-8.col-lg-7
    == render partial: "show_exercise_content", locals: {exercise: @exercise}

    => link_to 'Edit', edit_exercise_path(@exercise)
    '|
    =< link_to 'Back', exercises_path